### ISSUE TITLE
It doesn't seem to be picking up the 0.8.0 release...

### ISSUE THREAD

**Issue by dazoakley** [Banno/asdf-ksonnet#1]
Thanks for putting this together! :) 

Just noticed it doesn't seem to be picking up the 0.8.0 release from github:

```
$ asdf list-all kubecfg
0.1.0....
0.2.0
0.3.0
0.4.0
0.5.0
0.6.0
0.7.0
0.7.1
0.7.2
master
```

I would try and have a look at fixing it but I'm not sure where to start in the `list-all` scrip, my bash fu isn't that strong...

**Comment by nikolay** [comment]
Solved by https://github.com/Banno/asdf-ksonnet/pull/4
